### ISSUE TITLE
Update channel guide for 0.13

### ISSUE THREAD

**Issue by chrismccord** [phoenixframework/phoenix_guides#233]
I broke my own rules by pushing 0.13 without updating the guides first, but I promise I get things fixed up this evening

**Comment by lancehalvorsen** [comment]
:^)  I noticed.  :^)

I created a new version (v0.13.0) on the site and added the gist you created for upgrading from v0.12.0. I also updated the Up And Running Guide to use `mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v0.13.0/phoenix_new-0.13.0.ez` instead of the 0.12.0 version.

I'll poke around some more tonight to see if there is anything else that needs immediate attention.

**Comment by chrismccord** [comment]
Unless we list mix.exs deps somewhere, nothing else should need changed. `phoenix_html` was extracted, but everything else was backwards compat apart from channel changes

**Comment by lancehalvorsen** [comment]
First, I was totally kidding. Just want to make that clear. :^)

And, yes, we display the deps in mix.exs in a number of places, and we talk about changing them in a few places. This will be pretty easy to search for, though. 

I'm also going to just do a global search for "12". There are a number of places where we output results from commands that have version numbers in them. Again, this is easy to find and fix.

That should be really manageable.

**Comment by lancehalvorsen** [comment]
I must have been thinking of the Phoenix Guides from an alternate universe. There was hardly anything to change.

All changes from your work @chrismccord , as well as PR's and version bumps for this release have been moved over to phoenixframework.org. Yay!
