### ISSUE TITLE
Need to cover cross-compiling releases in exrm in the Advanced Deployment guide

### ISSUE THREAD

**Issue by gjaldon** [phoenixframework/phoenix_guides#254]
When doing a `mix release` in an OSX environment and then deploying that release to a different environment such as Ubuntu, you'll encounter the ff errors like the ff:

``` console
/opt/portal/erts-6.2.1/bin/run_erl: 1: /opt/portal/erts-6.2.1/bin/run_erl: Syntax error: Unterminated quoted string
```

We'll need to mention this in the advanced deployment guide. Below are some resources I gathered on this:
https://github.com/bitwalker/exrm/pull/99
http://erlang.org/doc/installation_guide/INSTALL-CROSS.html#Build-and-Install-Procedure

**Comment by mpahrens** [comment]
This probably doesn't help, but I hit this issue today deploying my phoenix app to a raspberry pi (compiled on ubuntu) and this issue was how I figured out what was wrong :) Thanks for the issue and I look forward to the updated guide!

**Comment by bitwalker** [comment]
See the solution in bitwalker/exrm#163, basically the steps are as follows:

1. Add `exrm` to your project
2. `$ mkdir -p rel && vim rel/relx.config`
3. Add `{include_erts, <path to lib/erlang>}`
4. Run `mix release`

So for example, on my OSX machine, I have Erlang 17.5 installed with Homebrew, and the path I would add to `relx.config` to use it is: `/usr/local/Cellar/erlang/17.5/lib/erlang`. You can validate the path you are providing is correct because `$ ls <path>` should contain a folder named like `erts-X.X`.

**Comment by felipesere** [comment]
Do I need to have erlang installed on `<path>` on my host machine?
I have the following in my `relx.config`:  `{include_erts, '/usr/lib/erlang/lib'}.`
which matches the path in my Alpine Linux container.
When I do `mix release` now I get an error...

**Comment by mpahrens** [comment]
I did. I had to have a copy of the erlang that my target machine is going to use on the dev machine because it wants to grab it at compile time.

**Comment by bitwalker** [comment]
@felipesere When you set `{include_erts, "path"}`, path must refer to the location of the Erlang installation *which was built on the container or compatible architecture*. When you provide a path to `include_erts`, you are saying, "bundle the ERTS located at the given path when packaging this release". Meaning you need to build or install Erlang on your container or a Linux VM, then copy the install to your build machine so that it can be referenced via the path provided to `include_erts`.

Alternatively you can set `{include_erts, false}` to use whatever is installed on the host, but you can run into issues with NIFs there, since your release package will build them against your local Erlang installation, which won't necessarily match the deployed Erlang installation, and then stuff blows up at runtime. That's only an issue with NIFs though, pure Elixir/Erlang code is portable, so it boils down to choosing one of the two options based on your needs really.

**Comment by felipesere** [comment]
Setting it to `false` and not running `--dev` made the difference.
Thanks!
I think while a bit riskier, it is the better solution. Otherwise I have to have all my teammates put the Erlang in that path...

**Comment by bitwalker** [comment]
@felipesere Yes I'd say always use `{include_erts, false}` when deploying to another architecture than the build machine, unless you have need to bundle a cross-compiled ERTS (for instance if you have NIFs or dependencies with NIFs). It's not that it's riskier per se, just that it simply won't work, but it's certainly the lowest barrier to entry of the two options.

**Comment by maxim** [comment]
@bitwalker Hey, I'm trying to figure out a way to use exrm on OS X for deploy on Ubuntu, and I came up with a build process that:

- launches an ubuntu docker container with elixir
- mounts my host source code dir
- runs all the mix/release stuff inside the container
- kills the container

I wonder if this is a legit way of doing this. The only problem for me is that if I already built a release on OS X, this would just override it. Would it perhaps make sense for exrm to make artifacts unique per OS/architecture in the rel directory?

**Comment by maxim** [comment]
I spoke with @benwilson512 on IRC about this, and he advised to use COPY/ADD to get the source into the container instead of mounting the source dir, and then mount a the rel inside the container to some host directory (e.g. ubuntu_rel). This way original rel is intact. Another option here is to never mount anything, and just copy the artifact from the container into some host location. I think I'll end up going with the latter approach.

**Comment by bitwalker** [comment]
@maxim I'd recommend following Ben Wilson's advice, since it keeps the `rel` directory preserved on the host, and doesn't requite the copy of `rel` into the container during the release process (if you are doing hot upgrades, if not then this is moot).

**Comment by maxim** [comment]
@bitwalker yep, ended up with copying source into container, and mapping container rel into host's rel_linux, seems to work, thanks

**Comment by niklas** [comment]
An additional problem when mounting the whole project into the machine: some erlang libs with custom c_src are not compiled (again) in the machine, resulting in a wrong binary format in the release. (happened to be with https://github.com/tonyrog/afunix)

**Comment by jeregrine** [comment]
This sounds like out of scope for the phoenix guides. Distillery and Exrm covers this in their documentation.

**Comment by bitwalker** [comment]
@jeregrine That reminds me, are you planning to remove references to exrm in the Phoenix guides, now that it has been deprecated for ~1 year? If you want some help, give me a shout.

**Comment by Gazler** [comment]
@bitwalker The only existing reference to exrm is https://github.com/phoenixframework/phoenix/blob/767f1d818d6965ec9623ff4e29082ec77529ce99/guides/docs/endpoint.md#L148 - We should either delete it or update it so that it uses Elixir 1.4 applications and Distillery.

**Comment by bitwalker** [comment]
Oh nice, I hadn't glanced at the guides in a little while, but the last time I looked the advanced deployment guide still existed which referenced exrm, but it looks like that has all changed now, so other than the last reference you found, looks like it's all good!
