### ISSUE TITLE
Improve our calls to action

### ISSUE THREAD

**Issue by josevalim** [phoenixframework/phoenix_guides#259]
Somehow a follow up to #169.

Today, we have four call to actions on our page.

* Guides (up and running)
* Guides (up and running)
* Guides (channels)
* Elixir

We should improve this. At least, the channels call to action should be something more actionable, like running an existing application or an "up and running" focused on using channels. This may be too much work though, so I am all in for ideas.

Also, it would be nice to rename the current "Documentation" section. It is not really documentation. Maybe "Important links"? Currently /docs takes to "Mix tasks" and I think we could do a better job here.

Finally, we should clean up the "How tos". We have a bunch of upgrade stuff but those are very time sensitive... maybe it is about time to start making those blog posts so our "News" section has at least some activity? Then we can remove the current upgrades from the guides.

**Comment by lancehalvorsen** [comment]
Definitely agree on all of this. 

I would also like to add two new headers to the left nav - "Testing" and "Deployment". Testing would be all new files; the directory structure in the repo already reflects this. Deployment would mimic that and move the deployment related guides into it from "Guides". This would leave the more "core" guide files under the Guides header. (Maybe rename "Guides" to "Core Guides" or something similar, but that's just a thought.)

**Comment by lancehalvorsen** [comment]
For the link to the Channels Guide:

Now  that we have a channel generator, we could re-work that guide to behave more like the Ecto Models Guide - sort of a Let's Build a Channel Together kinda thing. That way, it would feel more like an Up and Running for Channels.

**Comment by lancehalvorsen** [comment]
Thoughts on the left nav. What about this flow?

- Guides
- Testing
- Deployment
- Bonus Guides  (or maybe just "Extras"?)
  - move the upgrading.* entries to the "News" as @josevalim suggested
  - combine "Documentation" entries with "How To" entries. re-order/weed as needed

**Comment by josevalim** [comment]
That sounds great to me. I think we need one section though that will come before the Guides which is "Important links" (or another better name). Right now it should contain the "Community" page but I can imagine a "Learning" page coming soon as Phoenix books start to show up. Maybe we could move "Install" as a special page in there too. Out of the guide.

**Comment by lancehalvorsen** [comment]
Agreed. How about this?

- Introduction
  - Overview (current version, moved from Guides)
  - Installation (may overlap a lot with Up and Running, we'll see)
  - Learning (for now, we can extract stuff from Resources)
- Guides
- Testing
- Deployment
- Bonus Guides

**Comment by josevalim** [comment]
Sounds good to me! Overview can be guides in though. The first step of the guides. But anywhere is fine really. :)

**Comment by lancehalvorsen** [comment]
:+1:

**Comment by lancehalvorsen** [comment]
Ok, I think this is finally covered. I'll leave this open for a while until folks are back from NDC Oslo. 

Here's what I've done, all of it is live on the site:
- Renamed top left nav subhed "Introduction"
  - moved "Overview" up into it
  - pointed the "Guides" link in top nav to it instead of "Mix Tasks"
  - added a new "Installation" guide with extracted bits from "Overview"
  - re-worked the "Community" guide
  - split the former "Resources" into "Learning" for Phoenix and "Learning Elixir and Erlang"
    - "Learning" in the introduction, "Learning Elixir and Erlang" in the new "Bonus Guides"

- Created a new "Testing" subhed 
  - new "Introduction" guide
  - new "Models" testing guide

- Created a new "Deployment" subhed
  - moved the two deployment guides in there
  - renamed them "Introduction" and "Exrm Releases"

- Renamed the bottom subhed "Bonus Guides"
  - moved all the upgrading Phoenix entries into the "News" section
  - left one upgrading guide in to point to the "News" section
  - re-worked all the guides in this section

**Comment by josevalim** [comment]
Hey @lancehalvorsen, I have just went through everything and it is really, really, really good. Fantastic work here!

**Comment by lancehalvorsen** [comment]
Thanks so much @josevalim! Very, very nice to hear such positive feedback. :heart:
