### ISSUE TITLE
Why has phoenixframework.org to be that slow?

### ISSUE THREAD

**Issue by optikfluffel** [phoenixframework/phoenix_guides#284]
It's only kind of _a first world problem_ but navigating through the page is really slow. I also heard this complaint a couple of times when I was trying to show friends how awesome Phoenix is (and/or read that on Twitter from people I follow). The latency for the document itself is about 1.5 seconds, sitting in Germany.
Added to this I don't really get why we need to load more than 1MB of Javascript for some Docs including (as it seems) Angular.js without making much use of it and on top of that make a 404-ing request to `http://www.phoenixframework.org/js/angular.min.js.map`.
Oh and wrangling the images through [ImageOptim](https://imageoptim.com) also made them 44.5% smaller (granted, that's only 8.6KB out of 19.8KB, but still unnecessary).

**Comment by lancehalvorsen** [comment]
Hi @optikfluffel, 
The guides are currently hosted with readme.io, so I can't really speak to performance or implementation questions. We made this decision last year as it allows us to focus on writing and documenting Phoenix itself instead of re-implementing features we get from readme.io - new versions with a few clicks, suggested edits from readers, new topics and pages with a few clicks, and so on.

**Comment by optikfluffel** [comment]
![ok](http://www.reactiongifs.com/wp-content/uploads/2013/05/yep.gif)
