### ISSUE TITLE
Troubleshooting guide

### ISSUE THREAD

**Issue by nettofarah** [phoenixframework/phoenix_guides#312]
Would it make sense to have a troubleshooting section?

I was just trying to run phoenix on a brand new ubuntu machine today and ran into 3 different problems. 
I'd love to write down the explanation and solution for each one of them but I can't necessarily find the best spot to include them.

**Comment by lancehalvorsen** [comment]
I think this would be a great idea! My sense is that it should be in the "bonus guides" directory, and I think that "Troubleshooting Guide" would be a fine name.

If you're up for submitting a PR to get this started, that would be great and much appreciated! Since you've had issues recently, and they are still fresh in your mind, you're in a really good position to do this. :)

**Comment by nettofarah** [comment]
That's great to know, @lancehalvorsen.
I'm gonna try to put something together soon.

Thanks

**Comment by lancehalvorsen** [comment]
:+1:   Thanks!
