### ISSUE TITLE
Upgrade instructions from 0.13.x -> 0.14

### ISSUE THREAD

**Issue by mpahrens** [phoenixframework/phoenix_guides#313]
Following the Instructions here:

http://www.phoenixframework.org/v0.14.0/blog

I hit the following error:
`Looking up alternatives for conflicting requirements on phoenix`
  `Activated version: 0.14.0`
 ` From phoenix_live_reload v0.4.0: ~> 0.13.0`
  `From mix.exs: ~> 0.14`
`** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies`

Because the version of phoenix_live_reload that the phoenix mix tasks set up in my mix.exs was `v0.4.0. `
I fixed this problem by manually changing the version of phoenix_live_reload to `v0.4.3`.

I don't know if you want to include that note in the news post about updating with the other mix deps stuff. I know that the news posts aren't versioned here, but this seemed like the most appropriate place for me to suggest.

Thanks!
Edit: the phoenix version that was generated when I made my project was v0.13.1.

**Comment by lancehalvorsen** [comment]
@mpahrens thanks so much for reporting this! I think that since this problem occurs around a specific version number during an upgrade, the news section is the way to go.

I'll be doing some small updates to the site later today, and will take care of this then.

Thanks again. This is the kind of thing that can really help people out. <3

**Comment by lancehalvorsen** [comment]
Thanks again. This is now live on phoenixframework.org.
