### ISSUE TITLE
Explanation of how to use ^params in controller

### ISSUE THREAD

**Issue by Alamoz** [phoenixframework/phoenix_guides#344]
I'm opening this issue because I'm stuck on a problem, but also because this should be explained in the documentation for controllers. Perhaps it is apparent for experienced Elixir users, but the compiler error message implies this is perhaps unique to Phoenix.

I have a controller where I want to apply a branching condition using one of the request parameters. The compiler doesn't like this and issues the error:  "cannot use ^_params["foo"] outside of match clauses". Here is the code:

def foo(conn, _params) do
  cond do
    ^params["bar"] ->
        # do something
    true ->
       # do something else
  end
end

Thanks!

**Comment by lancehalvorsen** [comment]
Hi @Alamoz, this is actually normal Elixir behavior you are seeing. A match clause has the match operator, which is the equal sign, in it. Pattern matching can also happen in a function head. Your example doesn't do any pattern matching.

If you want to use `cond`, you could do this:
```elixir
cond do
  params["bar"] == 12 -> do_stuff
  params["bar"] == 7 -> do_other_stuff
  true -> do_something_else
end
```

You could also use `case` like this:
```elixir
case params["bar"] do
  12 -> do_stuff
  7 -> do_other_stuff
  any_other_value -> do_something_else
end
```

Also, prepending an underscore to a variable conventionally means you aren't going to use it, and you just want to avoid compiler warnings. That means the function head of your action would be better written as this, without the underscore:
```elixir
def foo(conn, params) do
```

Since this is common Elixir behavior, I don't think we need to cover it in the guides. Thanks!

**Comment by lancehalvorsen** [comment]
Oh, and the upper caret symbol `^`  - aka the "hat operator" - is only needed for variables used on the left hand side of pattern matches to make sure they don't get re-bound to new values.

**Comment by Alamoz** [comment]
Thank you so much. I have three Elixir books, but Phoenix has been working so well for me I have hardly looked at them! Pretty cool, that you can use a framework without even understanding the language.

**Comment by lancehalvorsen** [comment]
:+1:

**Comment by Alamoz** [comment]
Looks like the carat symbol (^params["foo"]) is also required in Ecto queries even when on the right hand side, perhaps because the variable is embedded in the query string.
