### ISSUE TITLE
Install nodej.s should mention nvm

### ISSUE THREAD

**Issue by tianyi33** [phoenixframework/phoenix_guides#394]
Node.js moves pretty fast. Recently io.js and node.js converged. 
A couple of suggestions about installing node.js in the installation guide:

1. As mentioned above about the node.js and io.js merging. But this line in the guide might be confusing in the future for people never heard about io.js.

>  Note: io.js, which is an npm compatible platform originally based on Node.js, is not known to work with Phoenix.

2. Should mention [nvm](https://github.com/creationix/nvm) for node.js installation. Very easy to install uninstall. Does not pollute system libraries etc. Personally think it should be the recommended way to install node.js.

What do you guys think? If you think the suggestions can improve the guide, I will make pull request :)

**Comment by lancehalvorsen** [comment]
Hi @tianyi33, thanks very much for taking the time to submit this suggestion! My sense is that we don't want to get into too much detail about installing node in these guides. For all the external dependencies, we point to the download/installation resources for that dependency because they are the most likely to be up to date. And honestly, the node site itself doesn't even mention nvm for installation, so I don't think we should.

I did notice that the download link no longer points to a reasonable page, though, so I'll fix that now.

Thanks again!

**Comment by tianyi33** [comment]
:+1:
