### ISSUE TITLE
Add Presence Guide

### ISSUE THREAD

**Issue by willykaram** [phoenixframework/phoenix_guides#497]
Given that Phoenix 1.2.0-rc has been released with `Phoenix.Presence` feature, as mentioned here:

https://groups.google.com/forum/#!topic/phoenix-core/2f-iLioWB-0

This blog post and video could be helpful starting points:

https://dockyard.com/blog/2016/03/25/what-makes-phoenix-presence-special-sneak-peek

**Comment by ybur-yug** [comment]
@willykaram Have you begun any work on this?
I feel like it would be incredibly valuable.

**Comment by willykaram** [comment]
@ybur-yug yes, I've started on the draft of it, and should have a version ready in the next 1-2 weeks. It's be great to collaborate on this if you're interested in helping or reviewing? Are there any other guides or issues that are of interest to you? I'd be happy to help you with them or review what you create.

**Comment by ybur-yug** [comment]
@willykaram just replied to another comment of yours referencing this but opened my notifications in order of oldest to newest so saw this last. Woops.

I would love to collaborate. My work schedule varies but I generally have at least 1-2 hours a day I can contribute forgiving personal events etc that take priority. I'm trying to consciously start contributing to as much as I can w.r.t Phoenix because in my workplace we have been working with it pretty seriously.

Feel free to share where you are at. I won't lie, I'm far from an expert on Channels and their implementations at this time but have been meaning to dive in and this would provide a noble excuse. 

I have looked through all the issues in the repo w.r.t docs and I feel like this could add the most clear and present value but I'd love to hear any other main contributors give their two cents as to where my time could be best dedicated.

**Comment by blackfist** [comment]
@willykaram @ybur-yug Do you two still need help with this? I'm willing to jump in and invest some time here.

**Comment by jeregrine** [comment]
@willykaram any movement on this one?

**Comment by ybur-yug** [comment]
@blackfist I've been swamped but primarily am going to try to knock out the secure handling of parameters additions before this as its a bit smaller and I havent dove a ton into presence yet. But I'm happy to proofread and add notes to anything that is done with this one and chip in a bit as well :)
