### ISSUE TITLE
Markdown newlines preserved as <br> tags in compiled HTML

### ISSUE THREAD

**Issue by lpil** [phoenixframework/phoenix_guides#615]
Hiya

It seems that the compiled HTML is erroneously preserving line breaks in the markdown by converting them to `<br>` tags when compiled to HTML.

This is resulting in some [rather funky formatting in places](http://www.phoenixframework.org/docs/sending-email#section-sending-email-with-smtp).

I had a little look round but I can't see where this could be fixed as this repo seems to be without config. Is this a bug in ex_doc perhaps?

**Comment by Gazler** [comment]
@lpil There were two pages with this error, emails and channel testing (probably ones I updated yesterday.) It appears readme.io treats new lines in the markdown as line breaks instead of the usual `  ` at the end of the line.

Let me know if you see any other pages with this issue. This will no longer be an issue when we switch to hosting the guides on hexdocs.

**Comment by lpil** [comment]
Thanks :)
