### ISSUE TITLE
"Frank" is missing from web guide

### ISSUE THREAD

**Issue by aljachimiak** [phoenixframework/phoenix_guides#645]
On the bottom of the [adding-pages](http://www.phoenixframework.org/docs/adding-pages) page, the image is incorrect.  It says "Phoenix" instead of "Frank".

After a little poking, [the page in this repo](https://github.com/phoenixframework/phoenix_guides/blob/master/docs/adding_pages.md) that corresponds with the page I just mentioned, seems to have the correct image in place (It mentions Frank).

Perhaps the latest version needs to be deployed?

**Comment by tomfbiz** [comment]
It looks like this may be fixed but not deployed? This image (and the image further up the page, on line 60, which is getting a 404), are both working correctly in the md version:
https://github.com/tomfbiz/phoenix_guides/blob/master/docs/adding_pages.md

One strange thing I noticed is that these lines have not been changed in master since 2014, maybe that is a clue.

**Comment by chrismccord** [comment]
Once this goes up on hexdocs this will be fixed. Thanks!

**Comment by hvnsweeting** [comment]
Hello, I'm the one who created the duplicated issue of this. After more than 1 month, it still not on hexdocs? So I'm wondering should we close the issue when it still was not fixed, as that might make more users create new issues for the same problem?

**Comment by chrismccord** [comment]
We are still working on the overhaul, so hang tight!

**Comment by chrisarcand** [comment]
@hvnsweeting https://github.com/phoenixframework/phoenix_guides/issues/680 💙
